#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | Unsupported Contributions for OpenFOAM 
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright (C) 2011-2013 OpenFOAM Foundation 
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
#2013-10-26 Bruno Santos (wyldckat@github): Updated code and comments.
#------------------------------------------------------------------------------
# License
#     This file is a derivative work of OpenFOAM. 
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     getTecIO
#
# Description
#     Get TecIO library and unpack it.
#
#------------------------------------------------------------------------------
version=2009
packageDir=tecio${version}
zipFile=$packageDir.zip
url="http://download.tecplot.com/tecio/$version/$zipFile"

#------------------------------------------------------------------------------
# run from third-party directory only
cd ${0%/*} || exit 1
wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}
. etc/tools/ThirdPartyFunctions
#------------------------------------------------------------------------------


# get tar.gz file if required
if [ ! -d ${packageDir} ]
then
    downloadFile $zipFile $url

    if [ -e download/$zipFile ]
    then
        echo "unpack download/$zipFile"
        unzip download/$zipFile
    else
        echo "no download/$zipFile to unpack"
    fi
fi

echo "For more information about the TecIO library, visit:"
echo "   http://www.tecplot.com/Downloads/TecIOLibrary.aspx"
# ----------------------------------------------------------------- end-of-file
